default_context:
  project_name: 'zscore_main'
  project_slug: 'zscore_main'
  domain_main: 'localhost'
  domain_staging: 'stag.localhost'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'stag-localhost'
  secret_key: '32a5ae7ee1448367dac1bc530fee1bd4d655327150781c4adca609e5b9158cd703'
  first_superuser: 'admin@localhost.com'
  first_superuser_password: 'root#123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.localhost", "https://stag.localhost", "https://localhost", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@localhost.com'
  postgres_password: 'root123'
  pgadmin_default_user: 'admin@localhost.com'
  pgadmin_default_user_password: 'root#123'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'stag.localhost'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:root#123'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
